DROP DATABASE IF EXISTS remissionService;
DROP USER IF EXISTS `remission_service`@`%`;
CREATE DATABASE IF NOT EXISTS remissionService CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `remission_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `remissionService`.* TO `remission_service`@`%`;
FLUSH PRIVILEGES;

